config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   root "users#index"
   resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end


  # get "up" => "rails/health#show", as: :rails_health_check"
end
 

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, foreign_key: :post_id
  has_many :comments, foreign_key: :post_id

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def most_recent_comments
    comments.order(created_at: :desc).includes(:author).limit(5)
  end

  private

  def update_post_counter
    author.increment!(:post_counter)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # load_and_authorize_resourcecls

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end



  def new
    @post = Post.new
  end

  def create
    @post = @current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
      else
        format.html { render :new }
    end
  end

  private
  def post_params
      params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<div id="user-all-posts">
    <div class="user">
        <img class="user-img" src="<%= @user.photo %>" alt="User photo">
        <div class="name-posts-count">
            <h2 class="user-name"><%= link_to @user.name, user_path(@user) %></h2>

            <div class="user-posts-count"><p>Number of posts: <%= @user.post_counter %></p></div>
        </div>
    </div>

    <% flash.each do |name, message| -%>
        <div class="<%= name %>-flash">
          <%= message %>
        </div>
    <% end -%>

    <div id="posts-container">
        <% @posts.each_with_index do |post, i| %>
            <% five_recent_comments = post.five_recent_comments.includes(:user) %>
            <div class="each-post-container">
                <div id="each-post-info">
                  <h3 id="post-title"><%= link_to "#{post.title} ##{i + 1}", user_post_path(@user, post) %></h3>
                  <p id="post-text"><%= truncate(post.text, length: 100, omission: '.....') %></p>
                  <div id="post-counts">
                      <p id="count-text">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
                  </div>
                </div>
                <div id="post-comments">
                    <% if five_recent_comments.empty? %>
                        <p class="each-comment">No Comments found!</p>
                    <% else %>
                        <% five_recent_comments.each do |comment|%>
                            <p class="each-comment">@<%= comment.user.name %>: <%= comment.text %></p>
                        <% end %>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
    <%# <%= will_paginate %>
</div>

app/views/posts/new.html.erb
<h2>Add a new Post please.<h2>

<% flash.each do |name, message| -%>
    <div class="<%= name %>-flash">
      <%= message %>
    </div>
<% end -%>
<%= form_with model: [:user, @post], local: true, class: 'post-form' do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
      <%= form.label :text %>
      <%= form.text_area :text %>
      <%= form.submit "Add new Post" %>
    </div>
<% end %>

app/views/posts/show.html.erb
<div class="post-container">
    <div id="post-content">
        <div id="name-counts">
        <p id="each-post-name"><%= @post.title %> by <%= @post.author.name %></p>
        <p id="each-post-c-l">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
        </div>
        <p id="each-post-text"><%= @post.text %></p>
    </div>

    <div id="each-post-info">
        <h3 id="post-title"><%= link_to "#{@post.title} ##{i}", user_post_path(@user, @post) %></h3>
        <p id="post-text"><%= truncate(@post.text, length: 100, omission: '.....') %></p>
        <div id="post-counts">
            <p id="count-text">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
        </div>
    </div>

    <div id="comments-container">
        <% if @post.comments.empty? %>
            <p class="each-commnet">No comments yet!</p>
        <% else %>
            <% @post.comments.each do |comment| %>
                <div class='comment-delete'>
                 <p class="each-comment">@<%= comment.user.name %>: <%= comment.text %></p>

                 <% if can? :destroy, comment %>
                   <%= form_with(model: comment, url: user_post_comment_path(@post.author, @post, id: comment.id), method: :delete, id: 'delete-comment-form') do |form| %>
                    <%= form.submit "Delete Comment", id: 'delete-comment-submit' %>
                   <% end %>
                 <% end %>
                </div>
            <% end %>
        <% end %>
    </div>

    <% flash.each do |name, message| -%>
        <div class="<%= name %>-flash">
          <%= message %>
        </div>
    <% end -%>

    <% if can? :create, Comment %>
      <h2 class="add-comment"><%= link_to 'Comment on the Post!', new_user_post_comment_path(@post.author, @post) %><h2>
    <% end %>

    <% if can? :destroy, @post %>
        <%= form_with(model: @post, url: user_post_path(@post.author, @post), method: :delete, id: 'delete-post-form') do |form| %>
            <%= form.submit "Delete Post", id: 'delete-post-submit' %>
        <% end %>
    <% end %>
</div>